//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.30 at 03:00:16 PM CEST 
//


package registration.microservice.app.model.megatravel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the search.microservice.app.model.megatravel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: search.microservice.app.model.megatravel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link IstorijaRezervacije }
     * 
     */
    public IstorijaRezervacije createIstorijaRezervacije() {
        return new IstorijaRezervacije();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link StatusRezervacije }
     * 
     */
    public StatusRezervacije createStatusRezervacije() {
        return new StatusRezervacije();
    }

    /**
     * Create an instance of {@link StatusSobe }
     * 
     */
    public StatusSobe createStatusSobe() {
        return new StatusSobe();
    }

    /**
     * Create an instance of {@link Koordinate }
     * 
     */
    public Koordinate createKoordinate() {
        return new Koordinate();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Cenovnik }
     * 
     */
    public Cenovnik createCenovnik() {
        return new Cenovnik();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link Lokacija }
     * 
     */
    public Lokacija createLokacija() {
        return new Lokacija();
    }

    /**
     * Create an instance of {@link KategorijaSmestaja }
     * 
     */
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }

    /**
     * Create an instance of {@link Soba }
     * 
     */
    public Soba createSoba() {
        return new Soba();
    }

    /**
     * Create an instance of {@link TipSobe }
     * 
     */
    public TipSobe createTipSobe() {
        return new TipSobe();
    }

    /**
     * Create an instance of {@link Usluge }
     * 
     */
    public Usluge createUsluge() {
        return new Usluge();
    }

    /**
     * Create an instance of {@link Zauzece }
     * 
     */
    public Zauzece createZauzece() {
        return new Zauzece();
    }

    /**
     * Create an instance of {@link RezervacijaPoSobi }
     * 
     */
    public RezervacijaPoSobi createRezervacijaPoSobi() {
        return new RezervacijaPoSobi();
    }

}
