package ftn.uns.ac.rs.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ftn.uns.ac.rs.model.Lokacija;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@Repository
public interface LokacijaRepository extends JpaRepository<Lokacija, Long> {

}
