//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.24 at 01:31:54 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://model.app.modul.agentski/StatusSobe", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package agentski.modul.app.model.statussobe;
