//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 03:51:10 PM CEST 
//


package ftn.uns.ac.rs.SearchMicroservice.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element ref="{http://rs.ac.uns.ftn/Model}Soba"/&gt;
 *         &lt;element ref="{http://rs.ac.uns.ftn/Model}Usluga"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "soba",
    "usluga"
})
@XmlRootElement(name = "SobneUsluge")
@Entity
public class SobneUsluge {

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
    @XmlElement(name = "Soba", required = true)
    @ManyToOne(optional = false)
    protected Soba soba;
    @XmlElement(name = "Usluga", required = true)
    @ManyToOne(optional = false)
    protected Usluga usluga;

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the soba property.
     * 
     * @return
     *     possible object is
     *     {@link Soba }
     *     
     */
    public Soba getSoba() {
        return soba;
    }

    /**
     * Sets the value of the soba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Soba }
     *     
     */
    public void setSoba(Soba value) {
        this.soba = value;
    }

    /**
     * Gets the value of the usluga property.
     * 
     * @return
     *     possible object is
     *     {@link Usluga }
     *     
     */
    public Usluga getUsluga() {
        return usluga;
    }

    /**
     * Sets the value of the usluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usluga }
     *     
     */
    public void setUsluga(Usluga value) {
        this.usluga = value;
    }

}
