FROM openjdk:8
EXPOSE 8002
ADD /target/SynchronizationMicroservice-0.0.1-SNAPSHOT.jar SynchronizationMicroservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "SynchronizationMicroservice-0.0.1-SNAPSHOT.jar"]