package agentski.modul.app.controller;

import org.springframework.beans.factory.annotation.Autowired;

import agentski.modul.app.repository.CenovnikRepository;

/**
* Generated by Spring Data Generator on 25/05/2019
*/

public class CenovnikController {

	private CenovnikRepository cenovnikRepository;

	@Autowired
	public CenovnikController(CenovnikRepository cenovnikRepository) {
		this.cenovnikRepository = cenovnikRepository;
	}

}
