package agentski.modul.app.controller;

import org.springframework.beans.factory.annotation.Autowired;

import agentski.modul.app.repository.SmestajRepository;

/**
* Generated by Spring Data Generator on 25/05/2019
*/

public class SmestajController {

	private SmestajRepository smestajRepository;

	@Autowired
	public SmestajController(SmestajRepository smestajRepository) {
		this.smestajRepository = smestajRepository;
	}

}
