package agentski.modul.app.controller;

import org.springframework.beans.factory.annotation.Autowired;

import agentski.modul.app.repository.SobaRepository;

/**
* Generated by Spring Data Generator on 25/05/2019
*/

public class SobaController {

	private SobaRepository sobaRepository;

	@Autowired
	public SobaController(SobaRepository sobaRepository) {
		this.sobaRepository = sobaRepository;
	}

}
