package agentski.modul.app.controller;

import org.springframework.beans.factory.annotation.Autowired;

import agentski.modul.app.repository.TipSobeRepository;

/**
* Generated by Spring Data Generator on 25/05/2019
*/

public class TipSobeController {

	private TipSobeRepository tipSobeRepository;

	@Autowired
	public TipSobeController(TipSobeRepository tipSobeRepository) {
		this.tipSobeRepository = tipSobeRepository;
	}

}
