package agentski.modul.app.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import agentski.modul.app.modelDTO.SifarnikDTO;
import agentski.modul.app.service.UslugaService;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@RestController
@RequestMapping("/usluga")
public class UslugeController {

	@Autowired
	private UslugaService uslugaService;

	@GetMapping
	public ResponseEntity<List<SifarnikDTO>> getAll(){
		if(uslugaService.getAll() == null) {
			return new ResponseEntity<List<SifarnikDTO>>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<List<SifarnikDTO>>(uslugaService.getAll(), HttpStatus.OK);
	}
	
	@GetMapping(value = "/{id}")
	public ResponseEntity<SifarnikDTO> getById(@PathVariable Long id){
		if(uslugaService.getById(id) == null) {
			return new ResponseEntity<SifarnikDTO>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<SifarnikDTO>(uslugaService.getById(id), HttpStatus.OK);
	}
	
	@PostMapping
	public ResponseEntity<String> add(@RequestBody SifarnikDTO SifarnikDTO){
		if(uslugaService.add(SifarnikDTO)) {
			return new ResponseEntity<String>("Usluga je uspesno dodata!", HttpStatus.CREATED);
		}else {
			return new ResponseEntity<String>("Greska pri dodavanju usluge!", HttpStatus.CONFLICT);
		}
			
	}
	
	@DeleteMapping(value = "/{id}")
	public ResponseEntity<String> delete(@PathVariable Long id){
		if(uslugaService.delete(id)) {
			return new ResponseEntity<String>("Usluga je uspesno obrisana!", HttpStatus.OK);
		}else {
			return new ResponseEntity<String>("Usluga nije pronadjena!", HttpStatus.NOT_FOUND);
		}
	}

}
