package agentski.modul.app.controller;

import org.springframework.beans.factory.annotation.Autowired;

import agentski.modul.app.repository.UslugeRepository;

/**
* Generated by Spring Data Generator on 25/05/2019
*/

public class UslugeController {

	private UslugeRepository uslugeRepository;

	@Autowired
	public UslugeController(UslugeRepository uslugeRepository) {
		this.uslugeRepository = uslugeRepository;
	}

}
