package ftn.uns.ac.rs.SearchMicroservice.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import ftn.uns.ac.rs.SearchMicroservice.model.Rezervacija;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@Repository
public interface RezervacijaRepository extends JpaRepository<Rezervacija, Long>, JpaSpecificationExecutor<Rezervacija>{
	
}
