//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.03 at 09:30:19 PM CEST 
//


package adminski.modul.app.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the adminski.modul.app.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: adminski.modul.app.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }
    public TipSobe createTipSobe() {
        return new TipSobe();
    }
    public Agent createAgent() {
        return new Agent();
    }
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }
    public Komentar createKomentar() {
        return new Komentar();
    }
    public Korisnik createKorisnik() {
        return new Korisnik();
    }
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }
    public TipUsluge createTipUsluge() {
        return new TipUsluge();
    }

}
