//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.26 at 12:44:11 AM CEST 
//


package ftn.uns.ac.rs.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusKomentara" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datumKreiranja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="idSmestaj" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idKorisnik" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "KomentarDTO")
public class KomentarDTO {

    protected long id;
    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(required = true)
    protected String tekst;
    @XmlElement(required = true)
    protected String statusKomentara;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumKreiranja;
    protected long idSmestaj;
    protected long idKorisnik;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the tekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekst(String value) {
        this.tekst = value;
    }

    /**
     * Gets the value of the statusKomentara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusKomentara() {
        return statusKomentara;
    }

    /**
     * Sets the value of the statusKomentara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusKomentara(String value) {
        this.statusKomentara = value;
    }

    /**
     * Gets the value of the datumKreiranja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumKreiranja() {
        return datumKreiranja;
    }

    /**
     * Sets the value of the datumKreiranja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumKreiranja(XMLGregorianCalendar value) {
        this.datumKreiranja = value;
    }

    /**
     * Gets the value of the idSmestaj property.
     * 
     */
    public long getIdSmestaj() {
        return idSmestaj;
    }

    /**
     * Sets the value of the idSmestaj property.
     * 
     */
    public void setIdSmestaj(long value) {
        this.idSmestaj = value;
    }

    /**
     * Gets the value of the idKorisnik property.
     * 
     */
    public long getIdKorisnik() {
        return idKorisnik;
    }

    /**
     * Sets the value of the idKorisnik property.
     * 
     */
    public void setIdKorisnik(long value) {
        this.idKorisnik = value;
    }

}
