//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.26 at 12:44:11 AM CEST 
//


package ftn.uns.ac.rs.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ftn.uns.ac.rs.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ftn.uns.ac.rs.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link Sifarnik }
     * 
     */
    public Sifarnik createSifarnik() {
        return new Sifarnik();
    }

    /**
     * Create an instance of {@link CreateLokacijaRequest }
     * 
     */
    public CreateLokacijaRequest createCreateLokacijaRequest() {
        return new CreateLokacijaRequest();
    }

    /**
     * Create an instance of {@link Lokacija }
     * 
     */
    public Lokacija createLokacija() {
        return new Lokacija();
    }

    /**
     * Create an instance of {@link CreateLokacijaResponse }
     * 
     */
    public CreateLokacijaResponse createCreateLokacijaResponse() {
        return new CreateLokacijaResponse();
    }

    /**
     * Create an instance of {@link PorukaDTO }
     * 
     */
    public PorukaDTO createPorukaDTO() {
        return new PorukaDTO();
    }

    /**
     * Create an instance of {@link GetAllPorukaRequest }
     * 
     */
    public GetAllPorukaRequest createGetAllPorukaRequest() {
        return new GetAllPorukaRequest();
    }

    /**
     * Create an instance of {@link SobaDTO }
     * 
     */
    public SobaDTO createSobaDTO() {
        return new SobaDTO();
    }

    /**
     * Create an instance of {@link UpdateRezervisaneSobeResponse }
     * 
     */
    public UpdateRezervisaneSobeResponse createUpdateRezervisaneSobeResponse() {
        return new UpdateRezervisaneSobeResponse();
    }

    /**
     * Create an instance of {@link ShowCenovnikDTO }
     * 
     */
    public ShowCenovnikDTO createShowCenovnikDTO() {
        return new ShowCenovnikDTO();
    }

    /**
     * Create an instance of {@link RezervisaneSobe }
     * 
     */
    public RezervisaneSobe createRezervisaneSobe() {
        return new RezervisaneSobe();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link KategorijaSmestaja }
     * 
     */
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }

    /**
     * Create an instance of {@link Soba }
     * 
     */
    public Soba createSoba() {
        return new Soba();
    }

    /**
     * Create an instance of {@link TipSobe }
     * 
     */
    public TipSobe createTipSobe() {
        return new TipSobe();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Komentar }
     * 
     */
    public Komentar createKomentar() {
        return new Komentar();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link GetAllTipSmestajaResponse }
     * 
     */
    public GetAllTipSmestajaResponse createGetAllTipSmestajaResponse() {
        return new GetAllTipSmestajaResponse();
    }

    /**
     * Create an instance of {@link CreateSobneUslugeRequest }
     * 
     */
    public CreateSobneUslugeRequest createCreateSobneUslugeRequest() {
        return new CreateSobneUslugeRequest();
    }

    /**
     * Create an instance of {@link SobneUslugeDTO }
     * 
     */
    public SobneUslugeDTO createSobneUslugeDTO() {
        return new SobneUslugeDTO();
    }

    /**
     * Create an instance of {@link ShowSobaDTO }
     * 
     */
    public ShowSobaDTO createShowSobaDTO() {
        return new ShowSobaDTO();
    }

    /**
     * Create an instance of {@link Usluga }
     * 
     */
    public Usluga createUsluga() {
        return new Usluga();
    }

    /**
     * Create an instance of {@link CreateSobneUslugeResponse }
     * 
     */
    public CreateSobneUslugeResponse createCreateSobneUslugeResponse() {
        return new CreateSobneUslugeResponse();
    }

    /**
     * Create an instance of {@link ShowRezervacijaDTO }
     * 
     */
    public ShowRezervacijaDTO createShowRezervacijaDTO() {
        return new ShowRezervacijaDTO();
    }

    /**
     * Create an instance of {@link ShowRezervisaneSobeDTO }
     * 
     */
    public ShowRezervisaneSobeDTO createShowRezervisaneSobeDTO() {
        return new ShowRezervisaneSobeDTO();
    }

    /**
     * Create an instance of {@link GetAllAgentResponse }
     * 
     */
    public GetAllAgentResponse createGetAllAgentResponse() {
        return new GetAllAgentResponse();
    }

    /**
     * Create an instance of {@link ShowAgentDTO }
     * 
     */
    public ShowAgentDTO createShowAgentDTO() {
        return new ShowAgentDTO();
    }

    /**
     * Create an instance of {@link CreateCenovnikRequest }
     * 
     */
    public CreateCenovnikRequest createCreateCenovnikRequest() {
        return new CreateCenovnikRequest();
    }

    /**
     * Create an instance of {@link CenovnikDTO }
     * 
     */
    public CenovnikDTO createCenovnikDTO() {
        return new CenovnikDTO();
    }

    /**
     * Create an instance of {@link SobneUsluge }
     * 
     */
    public SobneUsluge createSobneUsluge() {
        return new SobneUsluge();
    }

    /**
     * Create an instance of {@link SmestajDTO }
     * 
     */
    public SmestajDTO createSmestajDTO() {
        return new SmestajDTO();
    }

    /**
     * Create an instance of {@link GetAllRezervisaneSobeRequest }
     * 
     */
    public GetAllRezervisaneSobeRequest createGetAllRezervisaneSobeRequest() {
        return new GetAllRezervisaneSobeRequest();
    }

    /**
     * Create an instance of {@link GetAllKorisnikResponse }
     * 
     */
    public GetAllKorisnikResponse createGetAllKorisnikResponse() {
        return new GetAllKorisnikResponse();
    }

    /**
     * Create an instance of {@link CreateRezervacijaRequest }
     * 
     */
    public CreateRezervacijaRequest createCreateRezervacijaRequest() {
        return new CreateRezervacijaRequest();
    }

    /**
     * Create an instance of {@link RezervacijaDTO }
     * 
     */
    public RezervacijaDTO createRezervacijaDTO() {
        return new RezervacijaDTO();
    }

    /**
     * Create an instance of {@link RezervisaneSobeDTO }
     * 
     */
    public RezervisaneSobeDTO createRezervisaneSobeDTO() {
        return new RezervisaneSobeDTO();
    }

    /**
     * Create an instance of {@link CreateKoordinateRequest }
     * 
     */
    public CreateKoordinateRequest createCreateKoordinateRequest() {
        return new CreateKoordinateRequest();
    }

    /**
     * Create an instance of {@link Koordinate }
     * 
     */
    public Koordinate createKoordinate() {
        return new Koordinate();
    }

    /**
     * Create an instance of {@link CreateSobaResponse }
     * 
     */
    public CreateSobaResponse createCreateSobaResponse() {
        return new CreateSobaResponse();
    }

    /**
     * Create an instance of {@link GetAllKategorijaSmestajaResponse }
     * 
     */
    public GetAllKategorijaSmestajaResponse createGetAllKategorijaSmestajaResponse() {
        return new GetAllKategorijaSmestajaResponse();
    }

    /**
     * Create an instance of {@link ShowSmestajDTO }
     * 
     */
    public ShowSmestajDTO createShowSmestajDTO() {
        return new ShowSmestajDTO();
    }

    /**
     * Create an instance of {@link GetAllSobneUslugeResponse }
     * 
     */
    public GetAllSobneUslugeResponse createGetAllSobneUslugeResponse() {
        return new GetAllSobneUslugeResponse();
    }

    /**
     * Create an instance of {@link AgentLoginRequest }
     * 
     */
    public AgentLoginRequest createAgentLoginRequest() {
        return new AgentLoginRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajResponse }
     * 
     */
    public CreateSmestajResponse createCreateSmestajResponse() {
        return new CreateSmestajResponse();
    }

    /**
     * Create an instance of {@link CreatePorukaResponse }
     * 
     */
    public CreatePorukaResponse createCreatePorukaResponse() {
        return new CreatePorukaResponse();
    }

    /**
     * Create an instance of {@link GetAllRezervisaneSobeResponse }
     * 
     */
    public GetAllRezervisaneSobeResponse createGetAllRezervisaneSobeResponse() {
        return new GetAllRezervisaneSobeResponse();
    }

    /**
     * Create an instance of {@link CreateSmestajRequest }
     * 
     */
    public CreateSmestajRequest createCreateSmestajRequest() {
        return new CreateSmestajRequest();
    }

    /**
     * Create an instance of {@link CreateSobaRequest }
     * 
     */
    public CreateSobaRequest createCreateSobaRequest() {
        return new CreateSobaRequest();
    }

    /**
     * Create an instance of {@link GetAllKomentarRequest }
     * 
     */
    public GetAllKomentarRequest createGetAllKomentarRequest() {
        return new GetAllKomentarRequest();
    }

    /**
     * Create an instance of {@link GetAllTipSobeResponse }
     * 
     */
    public GetAllTipSobeResponse createGetAllTipSobeResponse() {
        return new GetAllTipSobeResponse();
    }

    /**
     * Create an instance of {@link CreatePorukaRequest }
     * 
     */
    public CreatePorukaRequest createCreatePorukaRequest() {
        return new CreatePorukaRequest();
    }

    /**
     * Create an instance of {@link GetAllAgentRequest }
     * 
     */
    public GetAllAgentRequest createGetAllAgentRequest() {
        return new GetAllAgentRequest();
    }

    /**
     * Create an instance of {@link GetAllPorukaResponse }
     * 
     */
    public GetAllPorukaResponse createGetAllPorukaResponse() {
        return new GetAllPorukaResponse();
    }

    /**
     * Create an instance of {@link UpdateRezervisaneSobeRequest }
     * 
     */
    public UpdateRezervisaneSobeRequest createUpdateRezervisaneSobeRequest() {
        return new UpdateRezervisaneSobeRequest();
    }

    /**
     * Create an instance of {@link AgentLoginDTO }
     * 
     */
    public AgentLoginDTO createAgentLoginDTO() {
        return new AgentLoginDTO();
    }

    /**
     * Create an instance of {@link Cenovnik }
     * 
     */
    public Cenovnik createCenovnik() {
        return new Cenovnik();
    }

    /**
     * Create an instance of {@link AgentDTO }
     * 
     */
    public AgentDTO createAgentDTO() {
        return new AgentDTO();
    }

    /**
     * Create an instance of {@link GetAllSobneUslugeRequest }
     * 
     */
    public GetAllSobneUslugeRequest createGetAllSobneUslugeRequest() {
        return new GetAllSobneUslugeRequest();
    }

    /**
     * Create an instance of {@link GetAllKategorijaSmestajaRequest }
     * 
     */
    public GetAllKategorijaSmestajaRequest createGetAllKategorijaSmestajaRequest() {
        return new GetAllKategorijaSmestajaRequest();
    }

    /**
     * Create an instance of {@link CreateRezervacijaResponse }
     * 
     */
    public CreateRezervacijaResponse createCreateRezervacijaResponse() {
        return new CreateRezervacijaResponse();
    }

    /**
     * Create an instance of {@link AgentLoginResponse }
     * 
     */
    public AgentLoginResponse createAgentLoginResponse() {
        return new AgentLoginResponse();
    }

    /**
     * Create an instance of {@link CreateKoordinateResponse }
     * 
     */
    public CreateKoordinateResponse createCreateKoordinateResponse() {
        return new CreateKoordinateResponse();
    }

    /**
     * Create an instance of {@link CreateCenovnikResponse }
     * 
     */
    public CreateCenovnikResponse createCreateCenovnikResponse() {
        return new CreateCenovnikResponse();
    }

    /**
     * Create an instance of {@link GetAllUslugaRequest }
     * 
     */
    public GetAllUslugaRequest createGetAllUslugaRequest() {
        return new GetAllUslugaRequest();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaResponse }
     * 
     */
    public GetAllRezervacijaResponse createGetAllRezervacijaResponse() {
        return new GetAllRezervacijaResponse();
    }

    /**
     * Create an instance of {@link GetAllKorisnikRequest }
     * 
     */
    public GetAllKorisnikRequest createGetAllKorisnikRequest() {
        return new GetAllKorisnikRequest();
    }

    /**
     * Create an instance of {@link GetRezervacijaRequest }
     * 
     */
    public GetRezervacijaRequest createGetRezervacijaRequest() {
        return new GetRezervacijaRequest();
    }

    /**
     * Create an instance of {@link GetAllKomentarResponse }
     * 
     */
    public GetAllKomentarResponse createGetAllKomentarResponse() {
        return new GetAllKomentarResponse();
    }

    /**
     * Create an instance of {@link KomentarDTO }
     * 
     */
    public KomentarDTO createKomentarDTO() {
        return new KomentarDTO();
    }

    /**
     * Create an instance of {@link UpdateAgentResponse }
     * 
     */
    public UpdateAgentResponse createUpdateAgentResponse() {
        return new UpdateAgentResponse();
    }

    /**
     * Create an instance of {@link UpdateAgentRequest }
     * 
     */
    public UpdateAgentRequest createUpdateAgentRequest() {
        return new UpdateAgentRequest();
    }

    /**
     * Create an instance of {@link GetAllTipSmestajaRequest }
     * 
     */
    public GetAllTipSmestajaRequest createGetAllTipSmestajaRequest() {
        return new GetAllTipSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetAllUslugaResponse }
     * 
     */
    public GetAllUslugaResponse createGetAllUslugaResponse() {
        return new GetAllUslugaResponse();
    }

    /**
     * Create an instance of {@link GetAllTipSobeRequest }
     * 
     */
    public GetAllTipSobeRequest createGetAllTipSobeRequest() {
        return new GetAllTipSobeRequest();
    }

    /**
     * Create an instance of {@link ShowPorukaDTO }
     * 
     */
    public ShowPorukaDTO createShowPorukaDTO() {
        return new ShowPorukaDTO();
    }

    /**
     * Create an instance of {@link RezervisaneSobeType }
     * 
     */
    public RezervisaneSobeType createRezervisaneSobeType() {
        return new RezervisaneSobeType();
    }

}
