package ftn.uns.ac.rs.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2 2019-06-08T10:32:41.331+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://rs.ac.uns.ftn/Model", name = "ProducerPort")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProducerPort {

	@WebMethod(operationName = "CreateCenovnik")
	@WebResult(name = "CreateCenovnikResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateCenovnikResponse")
	public CreateCenovnikResponse createCenovnik(

			@WebParam(partName = "CreateCenovnikRequest", name = "CreateCenovnikRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateCenovnikRequest createCenovnikRequest);

	@WebMethod(operationName = "GetAllKategorijaSmestaja")
	@WebResult(name = "GetAllKategorijaSmestajaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllKategorijaSmestajaResponse")
	public GetAllKategorijaSmestajaResponse getAllKategorijaSmestaja(

			@WebParam(partName = "GetAllKategorijaSmestajaRequest", name = "GetAllKategorijaSmestajaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllKategorijaSmestajaRequest getAllKategorijaSmestajaRequest);

	@WebMethod(operationName = "CreateLokacija")
	@WebResult(name = "CreateLokacijaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateLokacijaResponse")
	public CreateLokacijaResponse createLokacija(

			@WebParam(partName = "CreateLokacijaRequest", name = "CreateLokacijaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateLokacijaRequest createLokacijaRequest);

	@WebMethod(operationName = "GetAllTipSobe")
	@WebResult(name = "GetAllTipSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllTipSobeResponse")
	public GetAllTipSobeResponse getAllTipSobe(

			@WebParam(partName = "GetAllTipSobeRequest", name = "GetAllTipSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllTipSobeRequest getAllTipSobeRequest);

	@WebMethod(operationName = "CreateRezervacija")
	@WebResult(name = "CreateRezervacijaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateRezervacijaResponse")
	public CreateRezervacijaResponse createRezervacija(

			@WebParam(partName = "CreateRezervacijaRequest", name = "CreateRezervacijaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateRezervacijaRequest createRezervacijaRequest);

	@WebMethod(operationName = "CreateSmestaj")
	@WebResult(name = "CreateSmestajResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateSmestajResponse")
	public CreateSmestajResponse createSmestaj(

			@WebParam(partName = "CreateSmestajRequest", name = "CreateSmestajRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateSmestajRequest createSmestajRequest);

	@WebMethod(operationName = "GetAllTipSmestaja")
	@WebResult(name = "GetAllTipSmestajaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllTipSmestajaResponse")
	public GetAllTipSmestajaResponse getAllTipSmestaja(

			@WebParam(partName = "GetAllTipSmestajaRequest", name = "GetAllTipSmestajaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllTipSmestajaRequest getAllTipSmestajaRequest);

	@WebMethod(operationName = "CreateSoba")
	@WebResult(name = "CreateSobaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateSobaResponse")
	public CreateSobaResponse createSoba(

			@WebParam(partName = "CreateSobaRequest", name = "CreateSobaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateSobaRequest createSobaRequest);

	@WebMethod(operationName = "GetAllUsluga")
	@WebResult(name = "GetAllUslugaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllUslugaResponse")
	public GetAllUslugaResponse getAllUsluga(

			@WebParam(partName = "GetAllUslugaRequest", name = "GetAllUslugaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllUslugaRequest getAllUslugaRequest);

	@WebMethod(operationName = "CreateKoordinate")
	@WebResult(name = "CreateKoordinateResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateKoordinateResponse")
	public CreateKoordinateResponse createKoordinate(

			@WebParam(partName = "CreateKoordinateRequest", name = "CreateKoordinateRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateKoordinateRequest createKoordinateRequest);

	@WebMethod(operationName = "GetAllKorisnik")
	@WebResult(name = "GetAllKorisnikResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllKorisnikResponse")
	public GetAllKorisnikResponse getAllKorisnik(

			@WebParam(partName = "GetAllKorisnikRequest", name = "GetAllKorisnikRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllKorisnikRequest getAllKorisnikRequest);

	@WebMethod(operationName = "GetAllAgent")
	@WebResult(name = "GetAllAgentResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllAgentResponse")
	public GetAllAgentResponse getAllAgent(

			@WebParam(partName = "GetAllAgentRequest", name = "GetAllAgentRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllAgentRequest getAllAgentRequest);

	@WebMethod(operationName = "UpdateAgent")
	@WebResult(name = "UpdateAgentResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "UpdateAgentResponse")
	public UpdateAgentResponse updateAgent(

			@WebParam(partName = "UpdateAgentRequest", name = "UpdateAgentRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") UpdateAgentRequest updateAgentRequest);

	@WebMethod(operationName = "GetAllKomentar")
	@WebResult(name = "GetAllKomentarResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllKomentarResponse")
	public GetAllKomentarResponse getAllKomentar(

			@WebParam(partName = "GetAllKomentarRequest", name = "GetAllKomentarRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllKomentarRequest getAllKomentarRequest);

	@WebMethod(operationName = "CreatePoruka")
	@WebResult(name = "CreatePorukaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreatePorukaResponse")
	public CreatePorukaResponse createPoruka(

			@WebParam(partName = "CreatePorukaRequest", name = "CreatePorukaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreatePorukaRequest createPorukaRequest);

	@WebMethod(operationName = "GetAllPoruka")
	@WebResult(name = "GetAllPorukaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllPorukaResponse")
	public GetAllPorukaResponse getAllPoruka(

			@WebParam(partName = "GetAllPorukaRequest", name = "GetAllPorukaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllPorukaRequest getAllPorukaRequest);

	@WebMethod(operationName = "CreateSobneUsluge")

	@WebResult(name = "CreateSobneUslugeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateSobneUslugeResponse")
	public CreateSobneUslugeResponse createSobneUsluge(

			@WebParam(partName = "CreateSobneUslugeRequest", name = "CreateSobneUslugeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") CreateSobneUslugeRequest createSobneUslugeRequest);

	@WebMethod(operationName = "GetAllSobneUsluge")

	@WebResult(name = "GetAllSobneUslugeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllPorukaResponse")
	public GetAllSobneUslugeResponse getAllSobneUsluge(

			@WebParam(partName = "GetAllSobneUslugeRequest", name = "GetAllSobneUslugeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllSobneUslugeRequest getAllSobneUslugeRequest);

	@WebMethod(operationName = "UpdateRezervisaneSobe")
	@WebResult(name = "UpdateRezervisaneSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "UpdateRezervisaneSobeResponse")
	public UpdateRezervisaneSobeResponse updateRezervisaneSobe(

			@WebParam(partName = "UpdateRezervisaneSobeRequest", name = "UpdateRezervisaneSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") UpdateRezervisaneSobeRequest updateRezervisaneSobeRequest);

	@WebMethod(operationName = "AgentLogin")
	@WebResult(name = "AgentLoginResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "AgentLoginResponse")
	public AgentLoginResponse agentLogin(

			@WebParam(partName = "AgentLoginRequest", name = "AgentLoginRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") AgentLoginRequest agentLoginRequest);

	@WebMethod(operationName = "GetAllRezervisaneSobe")
	@WebResult(name = "GetAllRezervisaneSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllRezervisaneSobeResponse")
	public GetAllRezervisaneSobeResponse getAllRezervisaneSobe(

			@WebParam(partName = "GetAllRezervisaneSobeRequest", name = "GetAllRezervisaneSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") GetAllRezervisaneSobeRequest getAllRezervisaneSobeRequest);
	
	@WebMethod(operationName = "ValidateToken")
	@WebResult(name = "ValidateTokenResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "ValidateTokenResponse")
	public ValidateTokenResponse validateToken(

			@WebParam(partName = "ValidateTokenRequest", name = "ValidateTokenRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") ValidateTokenRequest validateTokenRequest);

	@WebMethod(operationName = "AgentLogout")
	@WebResult(name = "AgentLogoutResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "AgentLogoutResponse")
	public AgentLogoutResponse agentLogout(

			@WebParam(partName = "AgentLogoutRequest", name = "AgentLogoutRequest", targetNamespace = "http://rs.ac.uns.ftn/Model") AgentLogoutRequest agentLogoutRequest);


}
