package ftn.uns.ac.rs.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-08T10:32:41.331+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://rs.ac.uns.ftn/Model", name = "ProducerPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProducerPort {

    @WebMethod(operationName = "GetAllStatusSobe")
    @WebResult(name = "GetAllStatusSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllStatusSobeResponse")
    public GetAllStatusSobeResponse getAllStatusSobe(

        @WebParam(partName = "GetAllStatusSobeRequest", name = "GetAllStatusSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllStatusSobeRequest getAllStatusSobeRequest
    );

    @WebMethod(operationName = "CreateCenovnik")
    @WebResult(name = "CreateCenovnikResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateCenovnikResponse")
    public CreateCenovnikResponse createCenovnik(

        @WebParam(partName = "CreateCenovnikRequest", name = "CreateCenovnikRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateCenovnikRequest createCenovnikRequest
    );

    @WebMethod(operationName = "GetAllLokacija")
    @WebResult(name = "GetAllLokacijaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllLokacijaResponse")
    public GetAllLokacijaResponse getAllLokacija(

        @WebParam(partName = "GetAllLokacijaRequest", name = "GetAllLokacijaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllLokacijaRequest getAllLokacijaRequest
    );

    @WebMethod(operationName = "GetAllCenovnik")
    @WebResult(name = "GetAllCenovnikResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllCenovnikResponse")
    public GetAllCenovnikResponse getAllCenovnik(

        @WebParam(partName = "GetAllCenovnikRequest", name = "GetAllCenovnikRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllCenovnikRequest getAllCenovnikRequest
    );

    @WebMethod(operationName = "GetAllKategorijaSmestaja")
    @WebResult(name = "GetAllKategorijaSmestajaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllKategorijaSmestajaResponse")
    public GetAllKategorijaSmestajaResponse getAllKategorijaSmestaja(

        @WebParam(partName = "GetAllKategorijaSmestajaRequest", name = "GetAllKategorijaSmestajaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllKategorijaSmestajaRequest getAllKategorijaSmestajaRequest
    );

    @WebMethod(operationName = "GetAllSoba")
    @WebResult(name = "GetAllSobaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllSobaResponse")
    public GetAllSobaResponse getAllSoba(

        @WebParam(partName = "GetAllSobaRequest", name = "GetAllSobaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllSobaRequest getAllSobaRequest
    );

    @WebMethod(operationName = "CreateLokacija")
    @WebResult(name = "CreateLokacijaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateLokacijaResponse")
    public CreateLokacijaResponse createLokacija(

        @WebParam(partName = "CreateLokacijaRequest", name = "CreateLokacijaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateLokacijaRequest createLokacijaRequest
    );

    @WebMethod(operationName = "GetAllZauzece")
    @WebResult(name = "GetAllZauzeceResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllZauzeceResponse")
    public GetAllZauzeceResponse getAllZauzece(

        @WebParam(partName = "GetAllZauzeceRequest", name = "GetAllZauzeceRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllZauzeceRequest getAllZauzeceRequest
    );

    @WebMethod(operationName = "GetAllTipSobe")
    @WebResult(name = "GetAllTipSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllTipSobeResponse")
    public GetAllTipSobeResponse getAllTipSobe(

        @WebParam(partName = "GetAllTipSobeRequest", name = "GetAllTipSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllTipSobeRequest getAllTipSobeRequest
    );

    @WebMethod(operationName = "CreateKoordinate")
    @WebResult(name = "CreateKoordinateResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateKoordinateResponse")
    public CreateKoordinateResponse createKoordinate(

        @WebParam(partName = "CreateKoordinateRequest", name = "CreateKoordinateRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateKoordinateRequest createKoordinateRequest
    );

    @WebMethod(operationName = "CreateZauzece")
    @WebResult(name = "CreateZauzeceResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateZauzeceResponse")
    public CreateZauzeceResponse createZauzece(

        @WebParam(partName = "CreateZauzeceRequest", name = "CreateZauzeceRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateZauzeceRequest createZauzeceRequest
    );

    @WebMethod(operationName = "CreateSmestaj")
    @WebResult(name = "CreateSmestajResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateSmestajResponse")
    public CreateSmestajResponse createSmestaj(

        @WebParam(partName = "CreateSmestajRequest", name = "CreateSmestajRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateSmestajRequest createSmestajRequest
    );

    @WebMethod(operationName = "GetAllTipSmestaja")
    @WebResult(name = "GetAllTipSmestajaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllTipSmestajaResponse")
    public GetAllTipSmestajaResponse getAllTipSmestaja(

        @WebParam(partName = "GetAllTipSmestajaRequest", name = "GetAllTipSmestajaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllTipSmestajaRequest getAllTipSmestajaRequest
    );

    @WebMethod(operationName = "CreateSoba")
    @WebResult(name = "CreateSobaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateSobaResponse")
    public CreateSobaResponse createSoba(

        @WebParam(partName = "CreateSobaRequest", name = "CreateSobaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateSobaRequest createSobaRequest
    );

    @WebMethod(operationName = "GetAllKoordinate")
    @WebResult(name = "GetAllKoordinateResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllKoordinateResponse")
    public GetAllKoordinateResponse getAllKoordinate(

        @WebParam(partName = "GetAllKoordinateRequest", name = "GetAllKoordinateRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllKoordinateRequest getAllKoordinateRequest
    );

    @WebMethod(operationName = "CreateStatusSobe")
    @WebResult(name = "CreateStatusSobeResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "CreateStatusSobeResponse")
    public CreateStatusSobeResponse createStatusSobe(

        @WebParam(partName = "CreateStatusSobeRequest", name = "CreateStatusSobeRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        CreateStatusSobeRequest createStatusSobeRequest
    );

    @WebMethod(operationName = "GetAllSmestaj")
    @WebResult(name = "GetAllSmestajResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllSmestajResponse")
    public GetAllSmestajResponse getAllSmestaj(

        @WebParam(partName = "GetAllSmestajRequest", name = "GetAllSmestajRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllSmestajRequest getAllSmestajRequest
    );

    @WebMethod(operationName = "GetAllUsluga")
    @WebResult(name = "GetAllUslugaResponse", targetNamespace = "http://rs.ac.uns.ftn/Model", partName = "GetAllUslugaResponse")
    public GetAllUslugaResponse getAllUsluga(

        @WebParam(partName = "GetAllUslugaRequest", name = "GetAllUslugaRequest", targetNamespace = "http://rs.ac.uns.ftn/Model")
        GetAllUslugaRequest getAllUslugaRequest
    );
}
