//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.26 at 12:44:11 AM CEST 
//


package ftn.uns.ac.rs.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="datumOd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="datumDo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="cena" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="nazivSmestaj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brojSoba" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element ref="{http://rs.ac.uns.ftn/Model}ShowRezervisaneSobeDTO" maxOccurs="unbounded"/>
 *         &lt;element name="imePrezimeKorisnik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "datumOd",
    "datumDo",
    "cena",
    "nazivSmestaj",
    "brojSoba",
    "showRezervisaneSobeDTO",
    "imePrezimeKorisnik"
})
@XmlRootElement(name = "ShowRezervacijaDTO")
public class ShowRezervacijaDTO {

    protected long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumOd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumDo;
    protected float cena;
    @XmlElement(required = true)
    protected String nazivSmestaj;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojSoba;
    @XmlElement(name = "ShowRezervisaneSobeDTO", required = true)
    protected List<ShowRezervisaneSobeDTO> showRezervisaneSobeDTO;
    @XmlElement(required = true)
    protected String imePrezimeKorisnik;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the cena property.
     * 
     */
    public float getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     */
    public void setCena(float value) {
        this.cena = value;
    }

    /**
     * Gets the value of the nazivSmestaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivSmestaj() {
        return nazivSmestaj;
    }

    /**
     * Sets the value of the nazivSmestaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivSmestaj(String value) {
        this.nazivSmestaj = value;
    }

    /**
     * Gets the value of the brojSoba property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojSoba() {
        return brojSoba;
    }

    /**
     * Sets the value of the brojSoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojSoba(BigInteger value) {
        this.brojSoba = value;
    }

    /**
     * Gets the value of the showRezervisaneSobeDTO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the showRezervisaneSobeDTO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShowRezervisaneSobeDTO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShowRezervisaneSobeDTO }
     * 
     * 
     */
    public List<ShowRezervisaneSobeDTO> getShowRezervisaneSobeDTO() {
        if (showRezervisaneSobeDTO == null) {
            showRezervisaneSobeDTO = new ArrayList<ShowRezervisaneSobeDTO>();
        }
        return this.showRezervisaneSobeDTO;
    }

    /**
     * Gets the value of the imePrezimeKorisnik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImePrezimeKorisnik() {
        return imePrezimeKorisnik;
    }

    /**
     * Sets the value of the imePrezimeKorisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImePrezimeKorisnik(String value) {
        this.imePrezimeKorisnik = value;
    }

}
