FROM openjdk:8
EXPOSE 9001
ADD /target/RegistrationMicroService-0.0.1-SNAPSHOT.jar RegistrationMicroService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "RegistrationMicroService-0.0.1-SNAPSHOT.jar"]