//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 03:51:10 PM CEST 
//


package ftn.uns.ac.rs.ReservationMicroservice.dto;

import java.sql.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import ftn.uns.ac.rs.ReservationMicroservice.model.Korisnik;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}Long"/&gt;
 *         &lt;element name="datumOd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="datumDo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="cena" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="idKorisnika" type="{http://www.w3.org/2001/XMLSchema}Long"/&gt;
 *         &lt;element name="idSmestaj" type="{http://www.w3.org/2001/XMLSchema}Long"/&gt;
 *         &lt;element ref="{http://rs.ac.uns.ftn/Model}RezervisaneSobeDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

	"idSmestaj",
    "idTipSobe",
    "brojSoba",
    "datumFrom",
    "datumTo",
    "idKorisnik"
})
@XmlRootElement(name = "RezervacijaDTO")
public class RezervacijaDTO {

    protected Long idSmestaj;
    protected List<Long> idTipSobe;
    protected List<Integer> brojSoba;
    protected Date datumFrom;
    protected Date datumTo;
    protected Long idKorisnik;
    /**
     * Gets the value of the id property.
     * 
     */
	public Long getIdSmestaj() {
		return idSmestaj;
	}
	public void setIdSmestaj(Long idSmestaj) {
		this.idSmestaj = idSmestaj;
	}
	public List<Long> getIdTipSobe() {
		return idTipSobe;
	}
	public void setIdTipSobe(List<Long> idTipSobe) {
		this.idTipSobe = idTipSobe;
	}
	
	public List<Integer> getBrojSoba() {
		return brojSoba;
	}
	public void setBrojSoba(List<Integer> brojSoba) {
		this.brojSoba = brojSoba;
	}
	public Date getDatumFrom() {
		return datumFrom;
	}
	public void setDatumFrom(Date datumFrom) {
		this.datumFrom = datumFrom;
	}
	public Date getDatumTo() {
		return datumTo;
	}
	public void setDatumTo(Date datumTo) {
		this.datumTo = datumTo;
	}
	public Long getIdKorisnik() {
		return idKorisnik;
	}
	public void setIdKorisnik(Long idKorisnik) {
		this.idKorisnik = idKorisnik;
	}
	
    
}
