//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 09:50:54 AM CEST 
//


package ftn.uns.ac.rs.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ftn.uns.ac.rs.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ftn.uns.ac.rs.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateLokacijaRequest }
     * 
     */
    public CreateLokacijaRequest createCreateLokacijaRequest() {
        return new CreateLokacijaRequest();
    }

    /**
     * Create an instance of {@link LokacijaDTO }
     * 
     */
    public LokacijaDTO createLokacijaDTO() {
        return new LokacijaDTO();
    }

    /**
     * Create an instance of {@link CreateTipSobeRequest }
     * 
     */
    public CreateTipSobeRequest createCreateTipSobeRequest() {
        return new CreateTipSobeRequest();
    }

    /**
     * Create an instance of {@link TipSobeDTO }
     * 
     */
    public TipSobeDTO createTipSobeDTO() {
        return new TipSobeDTO();
    }

    /**
     * Create an instance of {@link GetAllTipSmestajaResponse }
     * 
     */
    public GetAllTipSmestajaResponse createGetAllTipSmestajaResponse() {
        return new GetAllTipSmestajaResponse();
    }

    /**
     * Create an instance of {@link TipSmestajaDTO }
     * 
     */
    public TipSmestajaDTO createTipSmestajaDTO() {
        return new TipSmestajaDTO();
    }

    /**
     * Create an instance of {@link KorisnikDTO }
     * 
     */
    public KorisnikDTO createKorisnikDTO() {
        return new KorisnikDTO();
    }

    /**
     * Create an instance of {@link CreateKorisnikRequest }
     * 
     */
    public CreateKorisnikRequest createCreateKorisnikRequest() {
        return new CreateKorisnikRequest();
    }

    /**
     * Create an instance of {@link GetByIdZauzeceRequest }
     * 
     */
    public GetByIdZauzeceRequest createGetByIdZauzeceRequest() {
        return new GetByIdZauzeceRequest();
    }

    /**
     * Create an instance of {@link CreateKorisnikResponse }
     * 
     */
    public CreateKorisnikResponse createCreateKorisnikResponse() {
        return new CreateKorisnikResponse();
    }

    /**
     * Create an instance of {@link CreateCenovnikRequest }
     * 
     */
    public CreateCenovnikRequest createCreateCenovnikRequest() {
        return new CreateCenovnikRequest();
    }

    /**
     * Create an instance of {@link CenovnikDTO }
     * 
     */
    public CenovnikDTO createCenovnikDTO() {
        return new CenovnikDTO();
    }

    /**
     * Create an instance of {@link SmestajDTO }
     * 
     */
    public SmestajDTO createSmestajDTO() {
        return new SmestajDTO();
    }

    /**
     * Create an instance of {@link GetAllKorisnikResponse }
     * 
     */
    public GetAllKorisnikResponse createGetAllKorisnikResponse() {
        return new GetAllKorisnikResponse();
    }

    /**
     * Create an instance of {@link Lokacija }
     * 
     */
    public Lokacija createLokacija() {
        return new Lokacija();
    }

    /**
     * Create an instance of {@link Koordinate }
     * 
     */
    public Koordinate createKoordinate() {
        return new Koordinate();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaPoSobiRequest }
     * 
     */
    public GetAllRezervacijaPoSobiRequest createGetAllRezervacijaPoSobiRequest() {
        return new GetAllRezervacijaPoSobiRequest();
    }

    /**
     * Create an instance of {@link CreateKoordinateRequest }
     * 
     */
    public CreateKoordinateRequest createCreateKoordinateRequest() {
        return new CreateKoordinateRequest();
    }

    /**
     * Create an instance of {@link KoordinateDTO }
     * 
     */
    public KoordinateDTO createKoordinateDTO() {
        return new KoordinateDTO();
    }

    /**
     * Create an instance of {@link CreateSobaResponse }
     * 
     */
    public CreateSobaResponse createCreateSobaResponse() {
        return new CreateSobaResponse();
    }

    /**
     * Create an instance of {@link CreateStatusSobeResponse }
     * 
     */
    public CreateStatusSobeResponse createCreateStatusSobeResponse() {
        return new CreateStatusSobeResponse();
    }

    /**
     * Create an instance of {@link GetByIdSmestajRequest }
     * 
     */
    public GetByIdSmestajRequest createGetByIdSmestajRequest() {
        return new GetByIdSmestajRequest();
    }

    /**
     * Create an instance of {@link GetAllStatusSobeRequest }
     * 
     */
    public GetAllStatusSobeRequest createGetAllStatusSobeRequest() {
        return new GetAllStatusSobeRequest();
    }

    /**
     * Create an instance of {@link GetByIdKoordinateRequest }
     * 
     */
    public GetByIdKoordinateRequest createGetByIdKoordinateRequest() {
        return new GetByIdKoordinateRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajResponse }
     * 
     */
    public CreateSmestajResponse createCreateSmestajResponse() {
        return new CreateSmestajResponse();
    }

    /**
     * Create an instance of {@link KategorijaSmestaja }
     * 
     */
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }

    /**
     * Create an instance of {@link GetByIdTipSmestajaRequest }
     * 
     */
    public GetByIdTipSmestajaRequest createGetByIdTipSmestajaRequest() {
        return new GetByIdTipSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetAllLokacijaRequest }
     * 
     */
    public GetAllLokacijaRequest createGetAllLokacijaRequest() {
        return new GetAllLokacijaRequest();
    }

    /**
     * Create an instance of {@link GetByIdTipSobeResponse }
     * 
     */
    public GetByIdTipSobeResponse createGetByIdTipSobeResponse() {
        return new GetByIdTipSobeResponse();
    }

    /**
     * Create an instance of {@link CreateZauzeceRequest }
     * 
     */
    public CreateZauzeceRequest createCreateZauzeceRequest() {
        return new CreateZauzeceRequest();
    }

    /**
     * Create an instance of {@link ZauzeceDTO }
     * 
     */
    public ZauzeceDTO createZauzeceDTO() {
        return new ZauzeceDTO();
    }

    /**
     * Create an instance of {@link CreateSobaRequest }
     * 
     */
    public CreateSobaRequest createCreateSobaRequest() {
        return new CreateSobaRequest();
    }

    /**
     * Create an instance of {@link SobaDTO }
     * 
     */
    public SobaDTO createSobaDTO() {
        return new SobaDTO();
    }

    /**
     * Create an instance of {@link GetAllTipSobeResponse }
     * 
     */
    public GetAllTipSobeResponse createGetAllTipSobeResponse() {
        return new GetAllTipSobeResponse();
    }

    /**
     * Create an instance of {@link GetAllIstorijaRezervacijeRequest }
     * 
     */
    public GetAllIstorijaRezervacijeRequest createGetAllIstorijaRezervacijeRequest() {
        return new GetAllIstorijaRezervacijeRequest();
    }

    /**
     * Create an instance of {@link GetByIdKorisnikResponse }
     * 
     */
    public GetByIdKorisnikResponse createGetByIdKorisnikResponse() {
        return new GetByIdKorisnikResponse();
    }

    /**
     * Create an instance of {@link StatusSobe }
     * 
     */
    public StatusSobe createStatusSobe() {
        return new StatusSobe();
    }

    /**
     * Create an instance of {@link CreateIstorijaRezervacijeResponse }
     * 
     */
    public CreateIstorijaRezervacijeResponse createCreateIstorijaRezervacijeResponse() {
        return new CreateIstorijaRezervacijeResponse();
    }

    /**
     * Create an instance of {@link GetAllSmestajResponse }
     * 
     */
    public GetAllSmestajResponse createGetAllSmestajResponse() {
        return new GetAllSmestajResponse();
    }

    /**
     * Create an instance of {@link GetAllSobaRequest }
     * 
     */
    public GetAllSobaRequest createGetAllSobaRequest() {
        return new GetAllSobaRequest();
    }

    /**
     * Create an instance of {@link GetByIdSmestajResponse }
     * 
     */
    public GetByIdSmestajResponse createGetByIdSmestajResponse() {
        return new GetByIdSmestajResponse();
    }

    /**
     * Create an instance of {@link CreateUslugaRequest }
     * 
     */
    public CreateUslugaRequest createCreateUslugaRequest() {
        return new CreateUslugaRequest();
    }

    /**
     * Create an instance of {@link UslugaDTO }
     * 
     */
    public UslugaDTO createUslugaDTO() {
        return new UslugaDTO();
    }

    /**
     * Create an instance of {@link CreateKategorijaSmestajaRequest }
     * 
     */
    public CreateKategorijaSmestajaRequest createCreateKategorijaSmestajaRequest() {
        return new CreateKategorijaSmestajaRequest();
    }

    /**
     * Create an instance of {@link KategorijaSmestajaDTO }
     * 
     */
    public KategorijaSmestajaDTO createKategorijaSmestajaDTO() {
        return new KategorijaSmestajaDTO();
    }

    /**
     * Create an instance of {@link GetAllSobaResponse }
     * 
     */
    public GetAllSobaResponse createGetAllSobaResponse() {
        return new GetAllSobaResponse();
    }

    /**
     * Create an instance of {@link GetByIdRezervacijaRequest }
     * 
     */
    public GetByIdRezervacijaRequest createGetByIdRezervacijaRequest() {
        return new GetByIdRezervacijaRequest();
    }

    /**
     * Create an instance of {@link CreateRezervacijaPoSobiRequest }
     * 
     */
    public CreateRezervacijaPoSobiRequest createCreateRezervacijaPoSobiRequest() {
        return new CreateRezervacijaPoSobiRequest();
    }

    /**
     * Create an instance of {@link RezervacijaPoSobiDTO }
     * 
     */
    public RezervacijaPoSobiDTO createRezervacijaPoSobiDTO() {
        return new RezervacijaPoSobiDTO();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaRequest }
     * 
     */
    public GetAllRezervacijaRequest createGetAllRezervacijaRequest() {
        return new GetAllRezervacijaRequest();
    }

    /**
     * Create an instance of {@link CreateKoordinateResponse }
     * 
     */
    public CreateKoordinateResponse createCreateKoordinateResponse() {
        return new CreateKoordinateResponse();
    }

    /**
     * Create an instance of {@link GetByIdLokacijaResponse }
     * 
     */
    public GetByIdLokacijaResponse createGetByIdLokacijaResponse() {
        return new GetByIdLokacijaResponse();
    }

    /**
     * Create an instance of {@link CreateCenovnikResponse }
     * 
     */
    public CreateCenovnikResponse createCreateCenovnikResponse() {
        return new CreateCenovnikResponse();
    }

    /**
     * Create an instance of {@link GetAllUslugaRequest }
     * 
     */
    public GetAllUslugaRequest createGetAllUslugaRequest() {
        return new GetAllUslugaRequest();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaResponse }
     * 
     */
    public GetAllRezervacijaResponse createGetAllRezervacijaResponse() {
        return new GetAllRezervacijaResponse();
    }

    /**
     * Create an instance of {@link RezervacijaDTO }
     * 
     */
    public RezervacijaDTO createRezervacijaDTO() {
        return new RezervacijaDTO();
    }

    /**
     * Create an instance of {@link GetAllCenovnikRequest }
     * 
     */
    public GetAllCenovnikRequest createGetAllCenovnikRequest() {
        return new GetAllCenovnikRequest();
    }

    /**
     * Create an instance of {@link Usluga }
     * 
     */
    public Usluga createUsluga() {
        return new Usluga();
    }

    /**
     * Create an instance of {@link Soba }
     * 
     */
    public Soba createSoba() {
        return new Soba();
    }

    /**
     * Create an instance of {@link TipSobe }
     * 
     */
    public TipSobe createTipSobe() {
        return new TipSobe();
    }

    /**
     * Create an instance of {@link Smestaj }
     * 
     */
    public Smestaj createSmestaj() {
        return new Smestaj();
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link GetByIdKategorijaSmestajaResponse }
     * 
     */
    public GetByIdKategorijaSmestajaResponse createGetByIdKategorijaSmestajaResponse() {
        return new GetByIdKategorijaSmestajaResponse();
    }

    /**
     * Create an instance of {@link GetAllKoordinateRequest }
     * 
     */
    public GetAllKoordinateRequest createGetAllKoordinateRequest() {
        return new GetAllKoordinateRequest();
    }

    /**
     * Create an instance of {@link GetAllZauzeceRequest }
     * 
     */
    public GetAllZauzeceRequest createGetAllZauzeceRequest() {
        return new GetAllZauzeceRequest();
    }

    /**
     * Create an instance of {@link GetAllTipSmestajaRequest }
     * 
     */
    public GetAllTipSmestajaRequest createGetAllTipSmestajaRequest() {
        return new GetAllTipSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetAllCenovnikResponse }
     * 
     */
    public GetAllCenovnikResponse createGetAllCenovnikResponse() {
        return new GetAllCenovnikResponse();
    }

    /**
     * Create an instance of {@link GetByIdLokacijaRequest }
     * 
     */
    public GetByIdLokacijaRequest createGetByIdLokacijaRequest() {
        return new GetByIdLokacijaRequest();
    }

    /**
     * Create an instance of {@link CreateLokacijaResponse }
     * 
     */
    public CreateLokacijaResponse createCreateLokacijaResponse() {
        return new CreateLokacijaResponse();
    }

    /**
     * Create an instance of {@link GetByIdRezervacijaResponse }
     * 
     */
    public GetByIdRezervacijaResponse createGetByIdRezervacijaResponse() {
        return new GetByIdRezervacijaResponse();
    }

    /**
     * Create an instance of {@link GetByIdRezervacijaPoSobiResponse }
     * 
     */
    public GetByIdRezervacijaPoSobiResponse createGetByIdRezervacijaPoSobiResponse() {
        return new GetByIdRezervacijaPoSobiResponse();
    }

    /**
     * Create an instance of {@link GetByIdCenovnikRequest }
     * 
     */
    public GetByIdCenovnikRequest createGetByIdCenovnikRequest() {
        return new GetByIdCenovnikRequest();
    }

    /**
     * Create an instance of {@link CreateUslugaResponse }
     * 
     */
    public CreateUslugaResponse createCreateUslugaResponse() {
        return new CreateUslugaResponse();
    }

    /**
     * Create an instance of {@link GetAllRezervacijaPoSobiResponse }
     * 
     */
    public GetAllRezervacijaPoSobiResponse createGetAllRezervacijaPoSobiResponse() {
        return new GetAllRezervacijaPoSobiResponse();
    }

    /**
     * Create an instance of {@link IstorijaRezervacijeDTO }
     * 
     */
    public IstorijaRezervacijeDTO createIstorijaRezervacijeDTO() {
        return new IstorijaRezervacijeDTO();
    }

    /**
     * Create an instance of {@link GetAllKoordinateResponse }
     * 
     */
    public GetAllKoordinateResponse createGetAllKoordinateResponse() {
        return new GetAllKoordinateResponse();
    }

    /**
     * Create an instance of {@link GetByIdKoordinateResponse }
     * 
     */
    public GetByIdKoordinateResponse createGetByIdKoordinateResponse() {
        return new GetByIdKoordinateResponse();
    }

    /**
     * Create an instance of {@link CreateRezervacijaRequest }
     * 
     */
    public CreateRezervacijaRequest createCreateRezervacijaRequest() {
        return new CreateRezervacijaRequest();
    }

    /**
     * Create an instance of {@link GetByIdSobaResponse }
     * 
     */
    public GetByIdSobaResponse createGetByIdSobaResponse() {
        return new GetByIdSobaResponse();
    }

    /**
     * Create an instance of {@link CreateTipSmestajaResponse }
     * 
     */
    public CreateTipSmestajaResponse createCreateTipSmestajaResponse() {
        return new CreateTipSmestajaResponse();
    }

    /**
     * Create an instance of {@link GetByIdUslugaRequest }
     * 
     */
    public GetByIdUslugaRequest createGetByIdUslugaRequest() {
        return new GetByIdUslugaRequest();
    }

    /**
     * Create an instance of {@link CreateTipSobeResponse }
     * 
     */
    public CreateTipSobeResponse createCreateTipSobeResponse() {
        return new CreateTipSobeResponse();
    }

    /**
     * Create an instance of {@link CreateZauzeceResponse }
     * 
     */
    public CreateZauzeceResponse createCreateZauzeceResponse() {
        return new CreateZauzeceResponse();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link GetAllLokacijaResponse }
     * 
     */
    public GetAllLokacijaResponse createGetAllLokacijaResponse() {
        return new GetAllLokacijaResponse();
    }

    /**
     * Create an instance of {@link GetAllKategorijaSmestajaResponse }
     * 
     */
    public GetAllKategorijaSmestajaResponse createGetAllKategorijaSmestajaResponse() {
        return new GetAllKategorijaSmestajaResponse();
    }

    /**
     * Create an instance of {@link StatusSobeDTO }
     * 
     */
    public StatusSobeDTO createStatusSobeDTO() {
        return new StatusSobeDTO();
    }

    /**
     * Create an instance of {@link GetByIdIstorijaRezervacijeRequest }
     * 
     */
    public GetByIdIstorijaRezervacijeRequest createGetByIdIstorijaRezervacijeRequest() {
        return new GetByIdIstorijaRezervacijeRequest();
    }

    /**
     * Create an instance of {@link CreateSmestajRequest }
     * 
     */
    public CreateSmestajRequest createCreateSmestajRequest() {
        return new CreateSmestajRequest();
    }

    /**
     * Create an instance of {@link RezervacijaPoSobi }
     * 
     */
    public RezervacijaPoSobi createRezervacijaPoSobi() {
        return new RezervacijaPoSobi();
    }

    /**
     * Create an instance of {@link IstorijaRezervacije }
     * 
     */
    public IstorijaRezervacije createIstorijaRezervacije() {
        return new IstorijaRezervacije();
    }

    /**
     * Create an instance of {@link GetAllIstorijaRezervacijeResponse }
     * 
     */
    public GetAllIstorijaRezervacijeResponse createGetAllIstorijaRezervacijeResponse() {
        return new GetAllIstorijaRezervacijeResponse();
    }

    /**
     * Create an instance of {@link GetByIdKategorijaSmestajaRequest }
     * 
     */
    public GetByIdKategorijaSmestajaRequest createGetByIdKategorijaSmestajaRequest() {
        return new GetByIdKategorijaSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetAllSmestajRequest }
     * 
     */
    public GetAllSmestajRequest createGetAllSmestajRequest() {
        return new GetAllSmestajRequest();
    }

    /**
     * Create an instance of {@link GetAllStatusSobeResponse }
     * 
     */
    public GetAllStatusSobeResponse createGetAllStatusSobeResponse() {
        return new GetAllStatusSobeResponse();
    }

    /**
     * Create an instance of {@link CreateIstorijaRezervacijeRequest }
     * 
     */
    public CreateIstorijaRezervacijeRequest createCreateIstorijaRezervacijeRequest() {
        return new CreateIstorijaRezervacijeRequest();
    }

    /**
     * Create an instance of {@link GetByIdTipSmestajaResponse }
     * 
     */
    public GetByIdTipSmestajaResponse createGetByIdTipSmestajaResponse() {
        return new GetByIdTipSmestajaResponse();
    }

    /**
     * Create an instance of {@link GetByIdRezervacijaPoSobiRequest }
     * 
     */
    public GetByIdRezervacijaPoSobiRequest createGetByIdRezervacijaPoSobiRequest() {
        return new GetByIdRezervacijaPoSobiRequest();
    }

    /**
     * Create an instance of {@link Cenovnik }
     * 
     */
    public Cenovnik createCenovnik() {
        return new Cenovnik();
    }

    /**
     * Create an instance of {@link GetAllKategorijaSmestajaRequest }
     * 
     */
    public GetAllKategorijaSmestajaRequest createGetAllKategorijaSmestajaRequest() {
        return new GetAllKategorijaSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetByIdIstorijaRezervacijeResponse }
     * 
     */
    public GetByIdIstorijaRezervacijeResponse createGetByIdIstorijaRezervacijeResponse() {
        return new GetByIdIstorijaRezervacijeResponse();
    }

    /**
     * Create an instance of {@link CreateRezervacijaResponse }
     * 
     */
    public CreateRezervacijaResponse createCreateRezervacijaResponse() {
        return new CreateRezervacijaResponse();
    }

    /**
     * Create an instance of {@link CreateKategorijaSmestajaResponse }
     * 
     */
    public CreateKategorijaSmestajaResponse createCreateKategorijaSmestajaResponse() {
        return new CreateKategorijaSmestajaResponse();
    }

    /**
     * Create an instance of {@link GetByIdUslugaResponse }
     * 
     */
    public GetByIdUslugaResponse createGetByIdUslugaResponse() {
        return new GetByIdUslugaResponse();
    }

    /**
     * Create an instance of {@link CreateStatusSobeRequest }
     * 
     */
    public CreateStatusSobeRequest createCreateStatusSobeRequest() {
        return new CreateStatusSobeRequest();
    }

    /**
     * Create an instance of {@link GetByIdTipSobeRequest }
     * 
     */
    public GetByIdTipSobeRequest createGetByIdTipSobeRequest() {
        return new GetByIdTipSobeRequest();
    }

    /**
     * Create an instance of {@link CreateRezervacijaPoSobiResponse }
     * 
     */
    public CreateRezervacijaPoSobiResponse createCreateRezervacijaPoSobiResponse() {
        return new CreateRezervacijaPoSobiResponse();
    }

    /**
     * Create an instance of {@link GetByIdSobaRequest }
     * 
     */
    public GetByIdSobaRequest createGetByIdSobaRequest() {
        return new GetByIdSobaRequest();
    }

    /**
     * Create an instance of {@link GetAllKorisnikRequest }
     * 
     */
    public GetAllKorisnikRequest createGetAllKorisnikRequest() {
        return new GetAllKorisnikRequest();
    }

    /**
     * Create an instance of {@link GetByIdZauzeceResponse }
     * 
     */
    public GetByIdZauzeceResponse createGetByIdZauzeceResponse() {
        return new GetByIdZauzeceResponse();
    }

    /**
     * Create an instance of {@link GetAllZauzeceResponse }
     * 
     */
    public GetAllZauzeceResponse createGetAllZauzeceResponse() {
        return new GetAllZauzeceResponse();
    }

    /**
     * Create an instance of {@link CreateTipSmestajaRequest }
     * 
     */
    public CreateTipSmestajaRequest createCreateTipSmestajaRequest() {
        return new CreateTipSmestajaRequest();
    }

    /**
     * Create an instance of {@link GetByIdCenovnikResponse }
     * 
     */
    public GetByIdCenovnikResponse createGetByIdCenovnikResponse() {
        return new GetByIdCenovnikResponse();
    }

    /**
     * Create an instance of {@link GetByIdKorisnikRequest }
     * 
     */
    public GetByIdKorisnikRequest createGetByIdKorisnikRequest() {
        return new GetByIdKorisnikRequest();
    }

    /**
     * Create an instance of {@link GetAllUslugaResponse }
     * 
     */
    public GetAllUslugaResponse createGetAllUslugaResponse() {
        return new GetAllUslugaResponse();
    }

    /**
     * Create an instance of {@link Zauzece }
     * 
     */
    public Zauzece createZauzece() {
        return new Zauzece();
    }

    /**
     * Create an instance of {@link GetAllTipSobeRequest }
     * 
     */
    public GetAllTipSobeRequest createGetAllTipSobeRequest() {
        return new GetAllTipSobeRequest();
    }

}
