//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 07:50:23 PM CEST 
//


package ftn.uns.ac.rs.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="datumOd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="datumDo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="brojSoba" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ukupnaCena" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "datumOd",
    "datumDo",
    "brojSoba",
    "ukupnaCena"
})
@XmlRootElement(name = "Rezervacija")
@Entity
public class Rezervacija {

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date datumOd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date datumDo;
    protected long brojSoba;
    protected float ukupnaCena;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDatumOd(Date value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDatumDo(Date value) {
        this.datumDo = value;
    }

    /**
     * Gets the value of the brojSoba property.
     * 
     */
    public long getBrojSoba() {
        return brojSoba;
    }

    /**
     * Sets the value of the brojSoba property.
     * 
     */
    public void setBrojSoba(long value) {
        this.brojSoba = value;
    }

    /**
     * Gets the value of the ukupnaCena property.
     * 
     */
    public float getUkupnaCena() {
        return ukupnaCena;
    }

    /**
     * Sets the value of the ukupnaCena property.
     * 
     */
    public void setUkupnaCena(float value) {
        this.ukupnaCena = value;
    }

}
