package agentski.modul.app.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import agentski.modul.app.model.smestaj.Smestaj;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@Repository
public interface SmestajRepository extends JpaRepository<Smestaj, Long> {

}
