package agentski.modul.app.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import agentski.modul.app.model.tipsobe.TipSobe;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@Repository
public interface TipSobeRepository extends JpaRepository<TipSobe, Long>{

}
