package ftn.uns.ac.rs.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ftn.uns.ac.rs.model.UslugaDTO;
import ftn.uns.ac.rs.service.UslugaService;

/**
* Generated by Spring Data Generator on 25/05/2019
*/
@RestController
@RequestMapping("/usluga")
public class UslugeController {

	@Autowired
	private UslugaService uslugaService;

	@GetMapping(value = "getAllSync")
	public ResponseEntity<List<UslugaDTO>> getAllSync(){
		return new ResponseEntity<List<UslugaDTO>>(uslugaService.getAllSync(), HttpStatus.OK);
	}
	
	@PostMapping(value = "createSync")
	public ResponseEntity<Integer> createSync(@RequestBody UslugaDTO UslugaDTO){
		
		return new ResponseEntity<Integer>(uslugaService.createSync(UslugaDTO), HttpStatus.OK);
	}
	
	@GetMapping
	public ResponseEntity<List<UslugaDTO>> getAll(){
		if(uslugaService.getAll() == null) {
			return new ResponseEntity<List<UslugaDTO>>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<List<UslugaDTO>>(uslugaService.getAll(), HttpStatus.OK);
	}
	
	@GetMapping(value = "/{id}")
	public ResponseEntity<UslugaDTO> getById(@PathVariable Long id){
		if(uslugaService.getById(id) == null) {
			return new ResponseEntity<UslugaDTO>(HttpStatus.NO_CONTENT);
		}
		return new ResponseEntity<UslugaDTO>(uslugaService.getById(id), HttpStatus.OK);
	}
	
	@PostMapping
	public ResponseEntity<String> add(@RequestBody UslugaDTO SifarnikDTO){
		if(uslugaService.add(SifarnikDTO)) {
			return new ResponseEntity<String>("Usluga je uspesno dodata!", HttpStatus.CREATED);
		}else {
			return new ResponseEntity<String>("Greska pri dodavanju usluge!", HttpStatus.CONFLICT);
		}
			
	}
	
	@DeleteMapping(value = "/{id}")
	public ResponseEntity<String> delete(@PathVariable Long id){
		if(uslugaService.delete(id)) {
			return new ResponseEntity<String>("Usluga je uspesno obrisana!", HttpStatus.OK);
		}else {
			return new ResponseEntity<String>("Usluga nije pronadjena!", HttpStatus.NOT_FOUND);
		}
	}

}
